/**
 * Critical FontAwesome icons used during initial render.
 * Keep this module small so startup does not load the full icon set.
 */

import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faCog,
  faCommentDots,
  faDatabase,
  faEdit,
  faEye,
  faEyeSlash,
  faFolder,
  faHome,
  faInfoCircle,
  faList,
  faMagnifyingGlass,
  faMinus,
  faPlus,
  faPlusCircle,
  faSearch,
  faStore,
  faTimes,
  faTrash,
  faWindowMaximize,
  faShieldAlt,
  faLaptopCode,
  faBug,
  faLock,
  faChevronUp,
  faChevronDown,
  faSquare,
  faArrowLeft,
  faCheckDouble,
  faExchangeAlt,
  faTrashAlt,
  faCheck,
  faArrowRotateRight,
  faRotateLeft,
  faArrowUpWideShort,
  faPuzzlePiece,
  faTrashCan,
} from "@fortawesome/free-solid-svg-icons";

import { faCircle } from "@fortawesome/free-regular-svg-icons";

export function registerCriticalIcons(): void {
  library.add(
    faHome,
    faCog,
    faPlus,
    faStore,
    faInfoCircle,
    faMinus,
    faWindowMaximize,
    faTimes,
    faList,
    faPlusCircle,
    faCommentDots,
    faSearch,
    faMagnifyingGlass,
    faFolder,
    faEdit,
    faEye,
    faEyeSlash,
    faTrash,
    faDatabase,
    faShieldAlt,
    faLaptopCode,
    faBug,
    faLock,
    faChevronUp,
    faChevronDown,
    faSquare,
    faCircle,
    faArrowLeft,
    faCheckDouble,
    faExchangeAlt,
    faTrashAlt,
    faCheck,
    faArrowRotateRight,
    faRotateLeft,
    faArrowUpWideShort,
    faPuzzlePiece,
    faTrashCan,
  );
}

export default { registerCriticalIcons };
