//! Save batch operations module - Handles batch editing and player data operations
//! Extracted from save_commands.rs for better modularity

use crate::cli_handlers;
use crate::common::{get_app_config_dir, get_save_games_dir, validate_save_games_path};
use crate::error::AppResult;
use crate::player_data;
use crate::save_editor;
use serde::Serialize;
use serde_json::json;
use serde_json::Value;
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::{Mutex, MutexGuard, OnceLock};

/// Helper: run a blocking closure via tokio::task::spawn_blocking,
/// mapping the join error into an AppResult.
async fn run_blocking<F, T>(f: F) -> AppResult<T>
where
    F: FnOnce() -> AppResult<T> + Send + 'static,
    T: Send + 'static,
{
    tokio::task::spawn_blocking(f)
        .await
        .map_err(|e| format!("Task was cancelled: {}", e))?
}

/// Get player data from a save file.
#[tauri::command]
pub async fn get_player_data(file_path: String) -> AppResult<Value> {
    run_blocking(move || {
        let path = Path::new(&file_path);
        validate_save_games_path(path)?;
        let save = cli_handlers::parse_sav_file(path)?;

        let (ids, sanities, inventories) = player_data::extract_player_data(&save);

        Ok(json!({
            "ids": ids,
            "sanities": sanities,
            "inventories": inventories
        }))
    })
    .await
}

/// Persistent cache of `steam id -> full PlayerData key` (`<steam id>_+_|<EOS PUID>`),
/// stored in the app config dir. Populated from existing saves so we don't have to
/// rescan every save on each lookup.
const PLAYER_ID_MAP_FILE: &str = "player_id_map.json";

/// Process-wide lock guarding the load → mutate → persist span over
/// `player_id_map.json`. Command bodies run on spawn_blocking threads and can
/// genuinely race (e.g. a create flow resolving a player id while the player
/// manager looks up another); without the lock one writer's discovery is lost.
static PLAYER_ID_MAP_LOCK: OnceLock<Mutex<()>> = OnceLock::new();

fn player_id_map_lock() -> MutexGuard<'static, ()> {
    PLAYER_ID_MAP_LOCK
        .get_or_init(|| Mutex::new(()))
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner())
}

fn player_id_map_path() -> AppResult<PathBuf> {
    Ok(get_app_config_dir()?.join(PLAYER_ID_MAP_FILE))
}

/// Load the cached player id map. Failures (missing/corrupt file) degrade to empty.
fn load_player_id_map() -> HashMap<String, String> {
    let Ok(path) = player_id_map_path() else {
        return HashMap::new();
    };
    let Ok(content) = fs::read_to_string(&path) else {
        return HashMap::new();
    };
    serde_json::from_str(&content).unwrap_or_default()
}

/// Persist the player id map (best-effort; a write failure only loses the cache).
fn save_player_id_map(map: &HashMap<String, String>) {
    let Ok(dir) = get_app_config_dir() else {
        return;
    };
    if !dir.exists() {
        let _ = fs::create_dir_all(&dir);
    }
    let Ok(json) = serde_json::to_string_pretty(map) else {
        return;
    };
    let _ = fs::write(dir.join(PLAYER_ID_MAP_FILE), json);
}

/// Pure player id: strip the `_+_|<suffix>` (online) or `-<15 chars>` (offline) part.
fn pure_player_key(id: &str) -> String {
    if let Some(idx) = id.find("_+_|") {
        id[..idx].to_string()
    } else if let Some(idx) = id.find('-') {
        id[..idx].to_string()
    } else {
        id.to_string()
    }
}

/// Whether the key carries a real EOS account id suffix: 32 hex chars and not the
/// all-zeros placeholder an earlier app version wrote. The game ignores keys with a
/// placeholder EOS id, so a create flow must never reuse one.
fn is_real_eos_key(key: &str) -> bool {
    if let Some(idx) = key.find("_+_|") {
        let suffix = &key[idx + 4..];
        suffix.len() == 32 && suffix != "00000000000000000000000000000000"
    } else {
        false
    }
}

/// Resolve the full PlayerData key (`<steam id>_+_|<EOS PUID>`) for a player id.
///
/// A bare steam id is not a usable PlayerData key: the game only binds player data
/// to `<steam id>_+_|<EOS PUID>` keys, so a bare-key entry is silently ignored
/// in-game (empty backpack, sanity reset to 100). The EOS PUID is generated by
/// Epic's servers per account and cannot be synthesized, so it must be read back
/// from a save (or the local cache) that already contains it.
///
/// - When `player_id` already carries a real (non-placeholder) EOS suffix it is
///   returned unchanged.
/// - Otherwise the local cache is checked, then existing saves are scanned; any
///   discovery is persisted for next time.
/// - Returns `None` when no real EOS key can be found anywhere (e.g. a player
///   that has never been saved — the game has no PUID for it yet).
pub(crate) fn resolve_player_full_key(player_id: &str) -> Option<String> {
    // Serialize the cache read-modify-write span (see PLAYER_ID_MAP_LOCK).
    let _guard = player_id_map_lock();

    // Already a real key — nothing to resolve.
    if is_real_eos_key(player_id) {
        return Some(player_id.to_string());
    }

    let mut map = load_player_id_map();
    // Cache hit must still pass the real-key check: older app versions persisted
    // all-zeros placeholders that the game ignores.
    if let Some(full) = map.get(player_id) {
        if is_real_eos_key(full) {
            return Some(full.clone());
        }
    }

    // Scan existing saves for a real EOS-suffixed entry belonging to this id.
    let mut discovered: Option<String> = None;
    if let Ok(save_games_dir) = get_save_games_dir() {
        if save_games_dir.exists() {
            let iter = walkdir::WalkDir::new(&save_games_dir)
                .max_depth(1)
                .into_iter()
                .filter_map(Result::ok)
                .filter(|e| e.file_type().is_file())
                .filter(|e| e.path().extension().is_some_and(|x| x == "sav"));

            'scan: for entry in iter {
                if let Ok(save) = cli_handlers::parse_sav_file(entry.path()) {
                    let (ids, _, _) = player_data::extract_player_data(&save);
                    for id in ids {
                        if is_real_eos_key(&id) && pure_player_key(&id) == player_id {
                            discovered = Some(id);
                            break 'scan;
                        }
                    }
                }
            }
        }
    }

    if let Some(full) = discovered {
        map.insert(player_id.to_string(), full.clone());
        save_player_id_map(&map);
        Some(full)
    } else {
        None
    }
}

/// Look up the full PlayerData key (`<steam id>_+_|<EOS PUID>`) for each requested
/// player. Checks the local cache first, then scans existing saves for missing ids and
/// updates the cache. The EOS PUID is generated by Epic's servers per account and cannot
/// be synthesized, so it must be read back from a save (or cache) that already contains it.
/// Returns a map: pure steam id -> full key (only for players found in saves/cache).
#[tauri::command]
pub async fn get_player_unique_ids(steam_ids: Vec<String>) -> AppResult<Value> {
    run_blocking(move || {
        // Serialize the cache read-modify-write span (see PLAYER_ID_MAP_LOCK).
        let _guard = player_id_map_lock();

        let mut map = load_player_id_map();

        // Only scan saves for ids missing from the cache. A cached entry only
        // counts as present when it carries a REAL EOS suffix: older versions
        // persisted all-zeros placeholders, and treating those as hits would
        // block the rediscovery scan forever (the result filter below would
        // keep dropping the placeholder, so the player could never resolve).
        let missing: Vec<String> = steam_ids
            .iter()
            .filter(|id| !map.get(*id).is_some_and(|full| is_real_eos_key(full)))
            .cloned()
            .collect();

        let mut discovered: HashMap<String, String> = HashMap::new();

        if !missing.is_empty() {
            if let Ok(save_games_dir) = get_save_games_dir() {
                if save_games_dir.exists() {
                    let iter = walkdir::WalkDir::new(&save_games_dir)
                        .max_depth(1)
                        .into_iter()
                        .filter_map(Result::ok)
                        .filter(|e| e.file_type().is_file())
                        .filter(|e| e.path().extension().is_some_and(|x| x == "sav"));

                    for entry in iter {
                        if let Ok(save) = cli_handlers::parse_sav_file(entry.path()) {
                            let (ids, _, _) = player_data::extract_player_data(&save);
                            for id in ids {
                                let pure = pure_player_key(&id);
                                if missing.contains(&pure) && is_real_eos_key(&id) {
                                    discovered.insert(pure, id);
                                }
                            }
                        }
                    }
                }
            }
        }

        // Merge discoveries into cache and persist
        for (pure, full) in discovered {
            map.insert(pure, full);
        }
        save_player_id_map(&map);

        // Build result map, filtering out keys without a real EOS suffix. The local cache
        // may still hold all-zeros placeholders written by an older version, so re-validate
        // every hit before handing it out.
        let result: HashMap<String, String> = steam_ids
            .into_iter()
            .filter_map(|id| {
                map.get(&id)
                    .filter(|full| is_real_eos_key(full))
                    .map(|full| (id, full.clone()))
            })
            .collect();

        Ok(json!({ "success": true, "map": result }))
    })
    .await
}

/// Unlock all hub doors in a save file.
#[tauri::command]
pub async fn unlock_all_hub_doors(file_path: String) -> AppResult<String> {
    run_blocking(move || {
        validate_save_games_path(Path::new(&file_path))?;
        save_editor::unlock_all_hub_doors(&file_path)
    })
    .await
}

/// Handle save file editing from JSON input.
#[tauri::command]
pub async fn handle_edit_save(json_input: Value) -> AppResult<String> {
    run_blocking(move || {
        let save_data = json_input
            .get("saveData")
            .ok_or("Missing 'saveData' in input")?;

        let output_dir = save_data
            .get("outputDir")
            .and_then(Value::as_str)
            .ok_or("Missing or invalid 'outputDir' in saveData")?;

        validate_save_games_path(Path::new(output_dir))?;

        let json_data = save_data
            .get("jsonData")
            .and_then(Value::as_object)
            .ok_or("Missing or invalid 'jsonData' in saveData")?;

        let json_value = Value::Object(json_data.clone());
        save_editor::edit_save_file(&json_value, output_dir)
    })
    .await
}

/// Result of a pre-flight archive-name availability check.
#[derive(Debug, Serialize)]
pub struct ArchiveNameCheck {
    /// false when the name+difficulty already maps to an existing .sav
    /// (other than the caller's own file, when `exclude_path` matches).
    pub available: bool,
    /// First available alternative like "Hotel (2)"; empty when available.
    pub suggestion: String,
}

/// Pre-flight check used by the create/edit UIs: mirrors create_new_save's
/// filename construction (`MULTIPLAYER_{name}_{sanitized difficulty}.sav`) so
/// the UI can warn BEFORE the backend's overwrite guard rejects the request,
/// and propose a name that is guaranteed to pass that guard.
///
/// `difficulty` must be the same string the caller will pass to
/// handle_new_save / handle_edit_save — it is sanitized with the exact same
/// alphanumeric filter create_new_save applies.
/// `exclude_path` lets the edit flow treat its OWN .sav as available
/// (keeping the current name must not be flagged as a conflict).
#[tauri::command]
pub async fn check_archive_name(
    name: String,
    difficulty: String,
    exclude_path: Option<String>,
) -> AppResult<ArchiveNameCheck> {
    run_blocking(move || {
        let name = name.trim();
        // Empty names never reach creation (it rejects them first), so report
        // available and let the regular validation surface the real problem.
        if name.is_empty() {
            return Ok(ArchiveNameCheck {
                available: true,
                suggestion: String::new(),
            });
        }

        // Mirror new_save.rs: difficulty is filtered to alphanumerics.
        let sanitized_difficulty: String =
            difficulty.chars().filter(|c| c.is_alphanumeric()).collect();

        let candidate_target = |candidate: &str| -> AppResult<PathBuf> {
            let file_name = format!("MULTIPLAYER_{}_{}.sav", candidate, sanitized_difficulty);
            let path = get_save_games_dir()?.join(file_name);
            validate_save_games_path(&path)?;
            Ok(path)
        };

        let target = candidate_target(name)?;
        // Filesystem-based sameness (canonicalize) rather than string compare:
        // the frontend-supplied path can differ in separators/case while naming
        // the same file — keeping the archive's own name is not a conflict.
        let is_own_file = exclude_path
            .as_deref()
            .map(|p| save_editor::is_same_save_target(Path::new(p), &target))
            .unwrap_or(false);
        let available = !target.exists() || is_own_file;
        if available {
            return Ok(ArchiveNameCheck {
                available: true,
                suggestion: String::new(),
            });
        }

        // Suggest the first free "name (2)" / "name (3)" … variant. Parentheses
        // and spaces are legal archive-name characters in both create and edit
        // flows, so the suggestion passes their filename-safety validation.
        let mut suggestion = String::new();
        for suffix in 2..=99 {
            let candidate = format!("{} ({})", name, suffix);
            if !candidate_target(&candidate)?.exists() {
                suggestion = candidate;
                break;
            }
        }
        // No suffix free (99 collisions): leave suggestion empty; the UI then
        // shows only the conflict without a one-click fix.
        Ok(ArchiveNameCheck {
            available: false,
            suggestion,
        })
    })
    .await
}
